travis:
  secure:
    BINSTAR_TOKEN: QnSCqbI4HbNo5YquKAkJMGhY7KVldwVYCfH8n8Gl617TCrQXMSW/BIeql8pbF6qq8zgBB3wJqvd8gX2VQSt7MvbaS8FU7zBDIHNQwh/IMNux7FQfIJt4JLI6lluBFbOBWUyUH9HSwzTiPNlx/QhhOXxpYnLa6w1kvbGw3JpIg6TP+vHGJE6z76g+a3xGemrV3sG5c0D5DHixXqPtdIinqnnMUgXAxGTS+s2dJyG5qmZGmaCszo9XuhWHsuZ3zx8sNnISjueZPand87ueZkHMSKxn/8+K2G6l41PNFAXzmWDAL2t2/Z+AysDdeBufCNf3+7qfrkLCPTsf/Sj05UD65G9Ha2D+Uj9kjESKYjSnMVhvtEvbf/bxhCtDe5BuKkBMLT2PDKprmelkH4vQMCH0Ali5N7DgaeWPHdkUdX1q5UshdVTIJsFYpjM01Jjrwuu0ZU3cQPiYapUS9MJoPx46fq3jzV24qljWAexyPwG+BqFqXCUYQDgOldxB4ap6PivEW7PZjNy5rzIe7txzTdxhgq7kRyFQrfKyf5vpP80+T/6Qj2VwV/S5kLhGc/YmqgmE82U314XS1lGUQGGXACgKWtbxSor+tXsGHhZvDJJV+QBx7LxC1TsAtrVQqAWfI5/YxrJmxSqLljkeMzaPT6oBbjT3Tm653H98OjaebJqrivM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
